name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  Cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Write the cypress.env.json file 📝
        run: |
          echo '${{ secrets.CYPRESS_ENV_CI }}' > cypress.env.json

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5.5.0 # use the explicit version number
        with:
          build: npm run build
          start: npm start
